---
- hosts: web
  become: true
  tasks:
   - name: stop running container
     shell: docker stop devopsjenk
     ignore_errors: yes
   - name: remove stopped container
     shell: docker rm devopsjenk
     ignore_errors: yes
   - name: run docker image
     shell: docker run -d --name devopsjenk -p 8090:8080 shivaswaroop40/devopsjenk
